-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Altera Program License
-- Subscription Agreement, Altera MegaCore Function License
-- Agreement, or other applicable license agreement, including,
-- without limitation, that your use is for the sole purpose of
-- programming logic devices manufactured by Altera and sold by
-- Altera or its authorized distributors.  Please refer to the
-- applicable agreement for further details.


-- Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
-- Created on Wed Nov 04 10:45:06 2015

LIBRARY ieee;
USE ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;


--  Entity Declaration

ENTITY ultra_sonar IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
clk : IN STD_LOGIC;
rst : IN STD_LOGIC;
enable : IN STD_LOGIC;
trigger : OUT STD_LOGIC
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END ultra_sonar;


--  Architecture Body

ARCHITECTURE ultra_sonar_architecture OF ultra_sonar IS
signal clkcount : std_logic_vector(20 downto 0);

BEGIN
PROCESS (rst,clk)
BEGIN
if rst = '1' then
	clkcount <= (others => '0');
	trigger <= '0';
elsif clk = '1' AND clk'event then
	if enable = '1' then
		if clkcount < 1500500 then
			if clkcount < 500 then
				trigger <= '1';
			else
				trigger <= '0';
			end if;
			clkcount <= clkcount + '1';
		else
			clkcount <= (others => '0');
		end if;
	else
		trigger <= '0';
	end if;
end if;


end process;
END ultra_sonar_architecture;
